language: objective-c
osx_image: xcode10
before_script:
    - bundle install
    - brew outdated carthage || brew upgrade carthage
script:
    - xcodebuild -project AloeStackView.xcodeproj -scheme AloeStackView -sdk iphonesimulator -destination "platform=iOS Simulator,OS=9.0,name=iPhone 6s" -configuration Debug -PBXBuildsContinueAfterErrors=0 SWIFT_VERSION=4.2 build test
    - xcodebuild -project AloeStackView.xcodeproj -scheme AloeStackView -sdk iphonesimulator -destination "platform=iOS Simulator,OS=9.0,name=iPhone 6s" -configuration Debug -PBXBuildsContinueAfterErrors=0 SWIFT_VERSION=4.0 build test
    - bundle exec pod lib lint --verbose --fail-fast
    - carthage build --verbose --no-skip-current
